### ISSUE TITLE
Prepare Marketplace - KYCC integration guide for CoinLoan

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/selfkey-lib#27]
https://github.com/SelfKeyFoundation/relying-party-mp-kycc-demo

**Comment by CortecKYC** [comment]
@sk91 What's left to do in this task?

**Comment by sk91** [comment]
Nothing, I just need @andregoncalves to give a quick review

**Comment by andregoncalves** [comment]
Looks great to me.
There's a few issues (like how do we keep the external KYC system requirements in sync with the KYCC template), but it's not worth thinking too much about them until we really need to.
